# Generated by Django 4.2.8 on 2023-12-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('phone', models.TextField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('dept', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
            ],
        ),
    ]
