# Generated by Django 4.2.8 on 2024-01-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_college_remove_userprofile_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
